ci: update ghc versions to match pinned nixpkgs
This should fix the travis failures, I think.

One issue with our nix setup is that ghc___Binary versions don't work
because they are treated differently in nixpkgs.

    > GHC_VERSION=ghc865Binary nix-build
    error: attribute 'haskellCompilerName' missing, at /nix/store/21wy3lycrr37p7i3czaz8mvrd576ckqm-source/pkgs/development/haskell-modules/make-package-set.nix:140:32
    (use '--show-trace' to show detailed location information)

For reference, here are all the ghc versions available

    > nix eval '(builtins.attrNames (import (builtins.fetchTarball (import ./nix/nixpkgs.nix)) {}).haskell.compiler)'
    [ "ghc8102Binary" "ghc8102BinaryMinimal" "ghc8104" "ghc865Binary" "ghc884" "ghc901" "ghcHEAD" "integer-simple" "native-bignum" ]